### PR TITLE
Add support for v3 of Pixelorama's .pxo format

### PR DESCRIPTION
**Pull request by benblank**
This change adds support for v3 .pxo files, as produced by Pixelorama v1.0 and later. It also extracts the handling of .pxo files from `…/export/pixelorama.gd` into separate scripts so that multiple versions can be more easily supported. The code for reading v2 files is left completely intact other than the changes required by moving it to `…/export/_pxo_v2.gd`.

The new `_export`/`_load_image` logic first attempts to read all .pxo files as though they use the v3 format. If that fails, the .pxo is read as a v2 file. If reading it as a v2 file is successful, the v2 result is used. Otherwise, the v3 result is used, regardless of whether it succeeded. The v3 format is tried first for the same reason that the v3 error is used if a file cannot be read at all — because v3 is the newer format, it will become more and more likely over time that users will be working with v3 files instead of v2 files.

*Note that while developing and testing this, I had the patch from 80829a6 applied, as I'm affected by #27/#33.*

### CODE REVIEW

**Comment by nklbdev** [comment]
Thank you! This is very much appreciated! I will check the work tomorrow.
Sorry, I had a lot of personal things to do. And I had problems with two-factor authentication on GitHub.

**Comment by nklbdev** [comment]
Thank you for waiting!!! I merged your pull-request and added several of my edits that were in the neighboring experimental branches to the main branch. Please check if everything works successfully for you.

Now the importer does not generate a separate PNG-image, but creates a `PortableCompressedTexture2D`. This resource is included in the output resource.

**Comment by nklbdev** [comment]
In the future I will try to refactor the code a little, do you mind?

**Comment by benblank** [comment]
> Please check if everything works successfully for you.

Yep, everything is working as expected with v3 .pxo files using the latest commit on main (7bada99). 🎉

> In the future I will try to refactor the code a little, do you mind?

Not at all! You're much more familiar with the codebase than I am, so if you see ways to improve anything, feel free. 🙂

**Pull request merged**
